version: '3'

services:
  mariadb:
    container_name: db
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_188618
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306
  memcached:
    container_name: BE_188618_memcached
    image: memcached
  prestashop:
    image: komeg1/be-prestashop-189642:1.0
    ports:
      - 18861:443
    depends_on:
      - mariadb
      - memcached
    ports:
      - 18861:443
    environment:
      PS_DEV_MODE: 0
    entrypoint: bash /db_dump/init_db.sh
    volumes:
      - ./prestashop/src:/var/www/html
      - ./prestashop.crt:/etc/ssl/certs/prestashop.crt
      - ./prestashop.key:/etc/ssl/private/prestashop.key
      - ./prestashop_ssl.conf:/etc/apache2/sites-available/prestashop_ssl.con
    command: 
      - /bin/bash
      - -c
      - |
        cp /etc/ssl/certs/prestashop.crt /usr/local/share/ca-certificates/prestashop.crt
        apt-get update 
        apt-get install -y libmemcached-dev zlib1g-dev 
        pecl install memcached 
        docker-php-ext-enable memcached
        update-ca-certificates
        a2ensite prestashop_ssl
        a2enmod ssl
        apache2-foreground