version: '3'
services:
  mariadb:
    container_name: db
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_188618
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7.8.10-apache
    restart: always
    depends_on:
      - mariadb
    ports:
      - 443:443
      - 18861:443
    environment:
      DB_SERVER: db
      DB_NAME: BE_188618
      DB_USER: root
      DB_PASSWD: student
      PS_INSTALL_AUTO: 0
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install  
      PS_LANGUAGE: pl
      PS_COUNTRY: PL
      PS_DEV_MODE: 1
    volumes:
      - ./prestashop/src:/var/www/html
      - ./prestashop.crt:/etc/ssl/certs/prestashop.crt
      - ./prestashop.key:/etc/ssl/private/prestashop.key
      - ./prestashop_ssl.conf:/etc/apache2/sites-available/prestashop_ssl.conf
    command: 
      - /bin/bash
      - -c
      - |
        cp /etc/ssl/certs/prestashop.crt /usr/local/share/ca-certificates/prestashop.crt
        update-ca-certificates
        a2ensite prestashop_ssl
        a2enmod ssl
        apache2-foreground